"""Strict enumerations for the semantic V2 shadow contract."""

from enum import StrEnum


class DialogueAct(StrEnum):
    NEW_TASK = "NEW_TASK"
    CONTINUE = "CONTINUE"
    MODIFY = "MODIFY"
    ADD = "ADD"
    REPLACE = "REPLACE"
    REMOVE = "REMOVE"
    CLEAR = "CLEAR"
    CORRECT = "CORRECT"
    DRILL_DOWN = "DRILL_DOWN"
    SWITCH_TOPIC = "SWITCH_TOPIC"
    RETURN_TO_TOPIC = "RETURN_TO_TOPIC"
    ANSWER_CLARIFICATION = "ANSWER_CLARIFICATION"
    CANCEL = "CANCEL"
    CONFIRM = "CONFIRM"
    FEEDBACK = "FEEDBACK"
    REFRESH = "REFRESH"
    REVISE = "REVISE"
    CHAT = "CHAT"


class ServiceRoute(StrEnum):
    CONTROL = "CONTROL"
    DATA_QUERY = "DATA_QUERY"
    DATASET_OPERATION = "DATASET_OPERATION"
    ANALYTICS = "ANALYTICS"
    METRIC_CATALOG = "METRIC_CATALOG"
    METADATA = "METADATA"
    LINEAGE = "LINEAGE"
    DATA_QUALITY = "DATA_QUALITY"
    FORECAST = "FORECAST"
    REPORTING = "REPORTING"
    CAPABILITY_HELP = "CAPABILITY_HELP"
    CHAT = "CHAT"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class AnalysisGoal(StrEnum):
    LOOKUP = "LOOKUP"
    AGGREGATE = "AGGREGATE"
    TREND = "TREND"
    COMPARE = "COMPARE"
    RANK = "RANK"
    COMPOSITION = "COMPOSITION"
    CORRELATION = "CORRELATION"
    ANOMALY = "ANOMALY"
    CONTRIBUTION = "CONTRIBUTION"
    ATTRIBUTION = "ATTRIBUTION"
    ROOT_CAUSE = "ROOT_CAUSE"
    FORECAST = "FORECAST"
    EXPLAIN = "EXPLAIN"


class QueryShape(StrEnum):
    CAPABILITY_HELP = "CAPABILITY_HELP"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    SCALAR_AGGREGATE = "SCALAR_AGGREGATE"
    GROUPED_AGGREGATE = "GROUPED_AGGREGATE"
    TIME_SERIES = "TIME_SERIES"
    RANKING = "RANKING"
    COMPARISON_SET = "COMPARISON_SET"
    RELATION_LIST = "RELATION_LIST"
    DETAIL_ROWS = "DETAIL_ROWS"
    DATASET_TRANSFORM = "DATASET_TRANSFORM"
    METADATA_LOOKUP = "METADATA_LOOKUP"
    LINEAGE_GRAPH = "LINEAGE_GRAPH"
    QUALITY_CHECK = "QUALITY_CHECK"
    ANOMALY_SERIES = "ANOMALY_SERIES"
    ROOT_CAUSE_PIPELINE = "ROOT_CAUSE_PIPELINE"
    FORECAST_SERIES = "FORECAST_SERIES"
    REPORT_PIPELINE = "REPORT_PIPELINE"
    CONTROL_ONLY = "CONTROL_ONLY"
    CHAT_ONLY = "CHAT_ONLY"


class CatalogType(StrEnum):
    ENTITY = "ENTITY"
    METRIC = "METRIC"
    DIMENSION = "DIMENSION"
    ATTRIBUTE = "ATTRIBUTE"
    ENTITY_VALUE = "ENTITY_VALUE"
    RELATION = "RELATION"
    DATASET = "DATASET"
    REPORT = "REPORT"
    PHYSICAL_TABLE = "PHYSICAL_TABLE"
    PHYSICAL_COLUMN = "PHYSICAL_COLUMN"


class SemanticRole(StrEnum):
    MEASURE = "MEASURE"
    GROUP_BY = "GROUP_BY"
    FILTER_FIELD = "FILTER_FIELD"
    FILTER_VALUE = "FILTER_VALUE"
    SOURCE_ENTITY = "SOURCE_ENTITY"
    TARGET_ENTITY = "TARGET_ENTITY"
    SUBJECT_ENTITY = "SUBJECT_ENTITY"
    PROJECTION_FIELD = "PROJECTION_FIELD"
    RELATIONSHIP = "RELATIONSHIP"
    RELATION_TARGET = "RELATION_TARGET"
    TIME_FIELD = "TIME_FIELD"
    TIME_RANGE = "TIME_RANGE"
    TIME_GRAIN = "TIME_GRAIN"
    COMPARISON_BASELINE = "COMPARISON_BASELINE"
    ORDER_BY = "ORDER_BY"
    SORT_DIRECTION = "SORT_DIRECTION"
    LIMIT = "LIMIT"
    DATASET_SOURCE = "DATASET_SOURCE"
    DELIVERY_TARGET = "DELIVERY_TARGET"


class ResolutionStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    AMBIGUOUS = "AMBIGUOUS"
    UNRESOLVED = "UNRESOLVED"


class SlotOperationType(StrEnum):
    KEEP = "KEEP"
    INHERIT = "INHERIT"
    SET = "SET"
    ADD = "ADD"
    REPLACE = "REPLACE"
    REMOVE = "REMOVE"
    CLEAR = "CLEAR"
    RESET_TASK = "RESET_TASK"


class Presence(StrEnum):
    UNSPECIFIED = "UNSPECIFIED"
    PRESENT = "PRESENT"
    EXPLICITLY_CLEARED = "EXPLICITLY_CLEARED"
    AMBIGUOUS = "AMBIGUOUS"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    INVALID = "INVALID"


class FilterOperator(StrEnum):
    AND = "AND"
    OR = "OR"
    NOT = "NOT"
    EQ = "EQ"
    NE = "NE"
    IN = "IN"
    NOT_IN = "NOT_IN"
    GT = "GT"
    GTE = "GTE"
    LT = "LT"
    LTE = "LTE"
    LIKE = "LIKE"
    NOT_LIKE = "NOT_LIKE"
    BETWEEN = "BETWEEN"
    IS_NULL = "IS_NULL"
    IS_NOT_NULL = "IS_NOT_NULL"


class TimeGrain(StrEnum):
    NONE = "NONE"
    DAY = "DAY"
    WEEK = "WEEK"
    MONTH = "MONTH"
    QUARTER = "QUARTER"
    YEAR = "YEAR"


class CalendarType(StrEnum):
    NATURAL = "NATURAL"
    FISCAL = "FISCAL"
    ROLLING = "ROLLING"


class MissingPeriodPolicy(StrEnum):
    LEAVE_MISSING = "LEAVE_MISSING"
    ZERO_FILL = "ZERO_FILL"
    NULL_FILL = "NULL_FILL"


class ProofStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class AdapterStatus(StrEnum):
    LOSSLESS = "LOSSLESS"
    LOSSY_COMPENSATED = "LOSSY_COMPENSATED"
    LOSSY_UNSAFE = "LOSSY_UNSAFE"
    UNSUPPORTED = "UNSUPPORTED"


class ErrorType(StrEnum):
    USER_AMBIGUITY = "USER_AMBIGUITY"
    SURFACE_PARSE_FAILURE = "SURFACE_PARSE_FAILURE"
    SEMANTIC_RESOLUTION_FAILURE = "SEMANTIC_RESOLUTION_FAILURE"
    PLAN_VALIDATION_FAILURE = "PLAN_VALIDATION_FAILURE"
    ASL_CONTRACT_FAILURE = "ASL_CONTRACT_FAILURE"
    SQL_PLAN_FAILURE = "SQL_PLAN_FAILURE"
    EXECUTION_FAILURE = "EXECUTION_FAILURE"
    RESULT_CONTRACT_FAILURE = "RESULT_CONTRACT_FAILURE"
    NO_DATA = "NO_DATA"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    DATA_NOT_READY = "DATA_NOT_READY"


class TaskVersionStatus(StrEnum):
    PROVISIONAL = "PROVISIONAL"
    RESOLVED = "RESOLVED"
    # Deprecated Python constants for 0.2 callers; never serialized as execution state.
    EXECUTABLE = "RESOLVED"
    EXECUTING = "RESOLVED"
    EXECUTED = "RESOLVED"
    FAILED = "RESOLVED"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"


class CandidateRejectionReason(StrEnum):
    SCOPE_MISMATCH = "SCOPE_MISMATCH"
    ROLE_MISMATCH = "ROLE_MISMATCH"
    FIELD_OWNERSHIP_MISMATCH = "FIELD_OWNERSHIP_MISMATCH"
    RELATION_UNREACHABLE = "RELATION_UNREACHABLE"
    METRIC_DIMENSION_INCOMPATIBLE = "METRIC_DIMENSION_INCOMPATIBLE"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    CATALOG_VERSION_MISMATCH = "CATALOG_VERSION_MISMATCH"
    DUPLICATE_RELATION = "DUPLICATE_RELATION"
    LOW_SCORE = "LOW_SCORE"
    AMBIGUOUS_SCORE = "AMBIGUOUS_SCORE"
    INVALID_GRAIN = "INVALID_GRAIN"
    JOIN_CARDINALITY_UNSAFE = "JOIN_CARDINALITY_UNSAFE"
    UNKNOWN_BUSINESS_RULE = "UNKNOWN_BUSINESS_RULE"


class ExecutionBackend(StrEnum):
    SEMANTIC_QUERY = "SEMANTIC_QUERY"
    DATASET_LOCAL = "DATASET_LOCAL"
    SEMANTIC_METADATA = "SEMANTIC_METADATA"
    ANALYTICS = "ANALYTICS"
    CHAT_RESPONSE = "CHAT_RESPONSE"
    CONTROL = "CONTROL"
    REPORT_COMPOSITION = "REPORT_COMPOSITION"


class ControlAction(StrEnum):
    CANCEL = "CANCEL"
    CONFIRM = "CONFIRM"
    REFRESH = "REFRESH"
    REVISE = "REVISE"


class DeliveryMode(StrEnum):
    TEXT = "TEXT"
    TABLE = "TABLE"
    CHART = "CHART"
    REPORT = "REPORT"
    EXPORT = "EXPORT"
    DASHBOARD = "DASHBOARD"


class Severity(StrEnum):
    BLOCKING = "BLOCKING"
    ADVISORY = "ADVISORY"


class ComparisonType(StrEnum):
    YOY = "YOY"
    MOM = "MOM"
    PERIOD_OVER_PERIOD = "PERIOD_OVER_PERIOD"
    ABSOLUTE_DELTA = "ABSOLUTE_DELTA"
    PERCENT_CHANGE = "PERCENT_CHANGE"
    RATIO = "RATIO"
    CUSTOM_PERIOD = "CUSTOM_PERIOD"


class Calculation(StrEnum):
    ABS_DIFF = "ABS_DIFF"
    PERCENT_DIFF = "PERCENT_DIFF"
    GROWTH_RATE = "GROWTH_RATE"
    RATIO = "RATIO"
    INDEX = "INDEX"


class QualityCheckType(StrEnum):
    FRESHNESS = "FRESHNESS"
    COMPLETENESS = "COMPLETENESS"
    NULL_RATE = "NULL_RATE"
    DUPLICATION = "DUPLICATION"
    CONSISTENCY = "CONSISTENCY"
    RECONCILIATION = "RECONCILIATION"


class ExecutionStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
